DEFAULT_CHAT_MODEL = "openai/gpt-5.2"
GROK_CHAT_MODEL = "xai/grok-4"
DEFAULT_IMAGE_MODEL = "google/nano-banana-pro"
DEFAULT_VIDEO_MODEL = "klingai/kling-v2.6/pro/image-to-video"
DEFAULT_MUSIC_MODEL = "mureka-ai/mureka-v8/generate-song"
